### ISSUE TITLE
My first voicemail triggered a callback, but subsequent ones did not

### ISSUE THREAD

**Issue by byrnereese** [ringcentral-tutorials/ringcentral-ai-bot#71]
Upon initially setting up the bot I was able to record a voicemail to myself, see the callback posted, and then have the bot message me. 

At the time I did not have Google setup to transcribe. So I signed up, and set my `.env` parameters accordingly. I then restarted my server, and tried again with a new voicemail. 

But I never saw the second callback. Or the third. 

I told the bot "AI Bot monitor" again and it confirmed it is monitoring my voicemail. I tried a fourth time, but no callback was received. 

How do I debug voicemails to make sure they are being captured, and that callbacks are being triggered?

**Comment by byrnereese** [comment]
I was forced to restart my computer by IT. This required me to setup a new ngrok, which prompted me to start from scratch. Remove the bot, and then re-add it. Update RedirectURI's etc. 

Despite these changes, my bot is not being notified on new voicemails.

**Comment by zxdong262** [comment]
@byrnereese restart ngrok will use new url, even old subscribe works, will send to old ngrok url, so after ngrok restart, need new subscribe,need do the auth again.
