### ISSUE TITLE
Change default sizes for documentation/code panes

### ISSUE THREAD

**Issue by byrnereese** [ringcentral-tutorials/ringcentral-ai-bot#79]
By default, viewsaurus has three columns with the following widths:

* prose - 30%
* code - fill
* explorer - 270 pixels

Often I feel when I load the documentation the prose column is too narrow, impacting readability. Could we increase the size to 40-50%? 

There are other style changes I would like to make/recommend which I can model in a fork, but I cannot find reliable documentation for viewsaurus. If someone can point me to the primary repository, or any developer resources, I can do some investigation on my own.

**Comment by zxdong262** [comment]
https://github.com/ringcentral-tutorials/ringcentral-ai-bot/commit/9b51a90e91e62ce4bedb884f05cd3e1944b542b5

Just edit css, seems ok.
